// Agent mappings are data, not generated engine-specific scripts. "do" stays
// compatible with the vocabulary of Search's original bench socket.
export const COMMANDS = Object.freeze({
  manifest: { description: 'Versioned command and adapter contract' },
  parity: { description: 'Compare this port with the original Search feature baseline' },
  probe: { description: 'Browser, tabs, active space, capabilities, and preferences' },
  tabs: { description: 'All tab metadata' },
  engines: { description: 'Installed renderer adapters and their capabilities' },
  require: { fields: { features: 'string[]' }, description: 'Require capabilities now and on later engine switches' },
  engine: { fields: { engine: 'registered engine ID', reload: 'boolean (explicit opt-in)' }, description: 'Stage a capability-checked renderer change with rollback on launch failure' },
  open: { fields: { url: 'HTTP(S) URL', private: 'boolean?', bench: 'boolean?', select: 'boolean?', space: 'space ID?' } },
  go: { fields: { id: 'tab ID?', url: 'HTTP(S) URL OR', text: 'address/search words' } },
  select: { fields: { id: 'tab ID' } },
  close: { fields: { id: 'tab ID or all (agent-owned tabs only)' } },
  reopen: { description: 'Reopen a normal closed tab; never reopens private tabs' },
  back: { fields: { id: 'tab ID?' } }, forward: { fields: { id: 'tab ID?' } }, reload: { fields: { id: 'tab ID?' } },
  wait: { fields: { id: 'tab ID?', seconds: 'number (0–60)?' } },
  text: { fields: { id: 'tab ID?' } },
  eval: { fields: { id: 'tab ID?', js: 'JavaScript expression' }, description: 'Evaluate in the remote page sandbox only; not exposed to the desktop shell' },
  click: { fields: { id: 'tab ID?', selector: 'CSS selector' } },
  type: { fields: { id: 'tab ID?', selector: 'CSS selector', text: 'string' } },
  submit: { fields: { id: 'tab ID?', selector: 'CSS selector' } },
  shot: { fields: { id: 'tab ID?', path: 'explicit local destination?' } },
  input: { fields: { id: 'tab ID?', kind: 'click | wheel | text | key', x: 'number?', y: 'number?', dx: 'number?', dy: 'number?', text: 'string?', key: 'key name?' } },
  find: { fields: { id: 'tab ID?', text: 'string', backward: 'boolean?' } },
  reader: { fields: { id: 'tab ID?' } },
  hide: { fields: { id: 'tab ID?', selector: 'CSS selector' } },
  bounds: { fields: { width: 'number (100–4096)', height: 'number (100–4096)' } },
  pin: { fields: { id: 'tab ID?', on: 'boolean?' } },
  sleep: { fields: { id: 'inactive normal tab ID' }, description: 'Keep ordinary forms, scroll, and session storage in memory; refuse secret fields, files, and playing media' },
  bookmark: { fields: { id: 'normal tab ID?' } },
  'bookmark-remove': { fields: { url: 'saved URL' } },
  'history-clear': {},
  settings: { fields: { search: 'HTTP(S) template containing %s?', look: 'system | light | dark?', sidebar: 'boolean?', shield: 'boolean?', pausedHost: 'hostname?' } },
  space: { fields: { action: 'new | go | swipe | rename | delete | move | move-tab', name: 'name for new?', id: 'ID for go?' } },
  group: { fields: { action: 'list | new | add | out | fold | rename | colour | icon | newtab | move | ungroup | close | reopen | bookmark | space', id: 'tab ID?', group: 'group ID?', name: 'string?', on: 'boolean?' } },
  'download-save': { fields: { id: 'tab ID?', path: 'explicit local destination', downloadId: 'download ID? (supports closed tabs)' } },
  devtools: { fields: { id: 'tab ID?' }, capability: 'devtools' },
  print: { fields: { id: 'tab ID?' }, capability: 'printing' },
  'renderer-set': { fields: { engine: 'registered engine ID' }, description: 'Use this renderer for new tabs; existing live pages keep their renderer and runtime. Sign-in stores stay separate.' },
  'renderer-map': { description: 'Live tab IDs mapped to their renderer IDs' },
  suggest: { fields: { text: 'string' }, description: 'Autocomplete from normal tabs, bookmarks, and history' },
  'search-tabs': { fields: { text: 'string' } },
  duplicate: { fields: { id: 'tab ID?' } }, rename: { fields: { id: 'tab ID?', name: 'string' } },
  place: { fields: { id: 'tab ID', index: 'zero-based integer' } },
  step: { fields: { backward: 'boolean?' } }, 'close-others': { fields: { id: 'tab ID?' } },
  'sleep-idle': { fields: { minutes: 'number?' }, description: 'Sleep eligible inactive normal tabs, preserving ordinary page state' },
  zoom: { fields: { id: 'tab ID?', factor: 'number?', reset: 'boolean?' } },
  library: { fields: { kind: 'bookmarks | history?', text: 'string?' } },
  'library-import': { fields: { data: '{bookmarks?: {url,title}[], history?: {url,title,at}[]}' }, description: 'Validate every entry before merging; reject executable URLs' },
  'library-export': { description: 'Portable JSON bookmarks and history export' },
  'bookmark-edit': { fields: { url: 'saved URL', newURL: 'HTTP(S) URL?', title: 'string?' } },
  'hidden-list': { fields: { id: 'tab ID?' } },
  unhide: { fields: { id: 'tab ID?', selector: 'CSS selector?', all: 'boolean?' } },
  'pick-hide': { fields: { id: 'tab ID?' }, description: 'Visual page picker; Escape cancels' },
  'shield-site': { fields: { id: 'tab ID?', on: 'boolean' } },
  'picture-in-picture': { fields: { id: 'tab ID?' }, capability: 'pictureInPicture' },
  'download-get': { fields: { id: 'tab ID?', downloadId: 'download ID?' }, description: 'Return download bytes (up to 64 MB) for the cloud controller' },
  password: { fields: { action: 'list | save | fill | remove | import', id: 'normal tab ID?', account: 'saved account ID?', username: 'string?', password: 'string?', csv: 'CSV text?' }, capability: 'passwords', description: 'OS-encrypted vault; list never returns passwords, filling verifies exact origin' },
  extensions: { capability: 'extensions' },
  'ext-folder': { fields: { path: 'local folder', yes: 'boolean? (after reviewing permissions)' }, capability: 'extensions' },
  'ext-add': { fields: { id: 'store ID or URL', yes: 'boolean? (after reviewing permissions)' }, capability: 'extensions', description: 'Verify CRX3 signature and extension identity before extracting' },
  'ext-remove': { fields: { id: 'extension ID' }, capability: 'extensions' },
  'ext-reload': { fields: { id: 'extension ID' }, capability: 'extensions' },
  'ext-enable': { fields: { id: 'extension ID', on: 'boolean' }, capability: 'extensions' },
  'ext-pin': { fields: { id: 'extension ID', on: 'boolean?' }, capability: 'extensions' },
  'ext-press': { fields: { id: 'extension ID' }, capability: 'extensions', description: 'Open popup and grant activeTab access for the selected normal tab' },
  'ext-page': { fields: { id: 'extension ID', path: 'relative extension page' }, capability: 'extensions' },
  'native-authorize': { fields: { extension: 'extension ID', host: 'registered host name', on: 'boolean' }, capability: 'nativeMessaging' },
  'native-connect': { fields: { extension: 'extension ID', host: 'registered host name' }, capability: 'nativeMessaging' },
  'native-post': { fields: { extension: 'extension ID', connection: 'connection ID', message: 'JSON' }, capability: 'nativeMessaging' },
  'native-poll': { fields: { extension: 'extension ID', connection: 'connection ID' }, capability: 'nativeMessaging' },
  'native-disconnect': { fields: { extension: 'extension ID', connection: 'connection ID' }, capability: 'nativeMessaging' },
  'update-check': { description: 'Verify an Ed25519-signed release feed; requires distributor configuration' },
  'update-stage': { fields: { manifest: 'result of update-check' }, description: 'Reverify feed, artifact signature metadata, exact size and SHA256; stage only' },
  tap: { fields: { id: 'tab ID?', selector: 'CSS selector or text=exact words' }, description: 'Trusted pointer input, unlike DOM click' },
  key: { fields: { id: 'tab ID?', text: 'string OR', key: 'key name' }, description: 'Portable page input alias' },
  resize: { fields: { width: 'number', height: 'number' }, description: 'Portable viewport bounds alias' },
});

// Status describes implementation, not an assertion of platform validation.
export const SEARCH_BASELINE = Object.freeze([
  { feature: 'Address and search', status: 'implemented', note: 'Six search engines, custom templates, local autocomplete, and external desktop links' },
  { feature: 'Tabs and session', status: 'implemented', note: 'Search, reorder, duplicate, rename, pin, close/reopen, lazy restore, zoom, and idle sleep with ordinary form/scroll recovery. Live heaps and page navigation stacks do not survive sleep/restart.' },
  { feature: 'Private browsing', capability: 'privateTabs', status: 'implemented', note: 'Memory-only per-tab stores; private tabs/history/bookmarks/groups/download records never persist' },
  { feature: 'Tab groups', status: 'implemented', note: 'Drag membership, colour, icon, fold, move, close/reopen, bookmark, and group-to-space' },
  { feature: 'Spaces', capability: 'spaces', status: 'implemented', note: 'Shared sign-ins by default or fresh isolated stores; switch, swipe command, rename, reorder, delete and move-tab' },
  { feature: 'Reader', capability: 'reader', status: 'implemented', note: 'Article extraction, lazy-image repair, known video embeds and return to page' },
  { feature: 'Hide elements', capability: 'hiddenElements', status: 'implemented', note: 'Visual picker, per-site review/restore, and document-start styles' },
  { feature: 'Shield', capability: 'shield', status: 'implemented', note: 'Original network/cosmetic rules, site overrides and Chromium service-worker request interception' },
  { feature: 'Bookmarks/history', status: 'implemented', note: 'Search, edit, remove, JSON import/export and HTML bookmark import in UI' },
  { feature: 'Downloads', capability: 'downloads', status: 'implemented', note: 'Download IDs preserve individual items; cloud byte download and desktop save dialogs' },
  { feature: 'Agent automation', status: 'partial', note: 'Shared versioned protocol on desktop/cloud; tap/key/resize aliases. Original AppKit-only film/hit/strip/column/press probes have no cross-platform equivalent; this is not a drop-in bench CLI.' },
  { feature: 'Devtools', capability: 'devtools', status: 'implemented', note: 'Electron native inspector' },
  { feature: 'Printing', capability: 'printing', status: 'partial', note: 'Electron print adapter; physical printer and OS dialog validation required' },
  { feature: 'Picture in picture', capability: 'pictureInPicture', status: 'implemented', note: 'Float the same live Chromium surface and return it without reload' },
  { feature: 'Passwords and import', capability: 'passwords', status: 'partial', note: 'OS-encrypted vault, exact-origin fill, settled-login save/update offers, manual save/remove and quoted CSV import; OS reauthentication/reveal and direct other-browser database import remain' },
  { feature: 'Passkeys', capability: 'passkeys', status: 'partial', note: 'Virtual WebAuthn authenticator tested in Electron; real hardware/system passkey providers require device validation' },
  { feature: 'Chrome extensions', capability: 'extensions', status: 'partial', note: 'Signed CRX3/store and unpacked install, lifecycle, content scripts, tab/window APIs, isolated top-frame scripting, activeTab grants. Additional Chrome API shims, workers, full extension corpus and private extension support need validation/work.' },
  { feature: 'Native messaging', capability: 'nativeMessaging', status: 'partial', note: 'Extension-origin/permission-scoped native messaging tested on Linux; Windows registry discovery implemented, actual Windows/macOS host validation remains' },
  { feature: 'Signed updates', status: 'partial', note: 'Ed25519 feed checks, freshness/device/version checks and size/SHA256-verified staging; production signing/feed and automatic platform installation remain' },
  { feature: 'Desktop packaging', status: 'partial', note: 'Linux unpacked app built; Linux/Windows/macOS distribution targets configured. Windows/macOS execution, signing/notarization and final installers need validation.' },
  { feature: 'Renderer interchange', status: 'partial', note: 'New-tab renderer routing preserves existing live heaps. Explicit reload migration transfers Playwright storage and ordinary forms/scroll; Electron/Swift native-store migration and Firefox/WebKit execution remain unverified.' },
  { feature: 'Native mobile hosts', status: 'missing', note: 'Responsive cloud controller includes touch input and soft keyboard, but cannot provide offline browsing, live audio, page accessibility, mobile vaults or native iOS/Android rendering.' },
]);

export function parityReport(adapter) {
  const baseline = SEARCH_BASELINE.map(item => ({ ...item, ...(item.capability ? { available: adapter.capabilities[item.capability] === true } : {}) }));
  return { complete: false, baseline, engine: adapter.id, capabilities: adapter.capabilities, remaining: baseline.filter(item => item.status !== 'implemented' || item.available === false) };
}
