import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Browser } from '../src/browser.js';
import { EngineRegistry } from '../src/contract.js';
import { ChromiumAdapter } from '../src/adapters/chromium.js';
import { Store } from '../src/store.js';

test('renderer routing keeps live heaps and private contexts, rolls back failure, and restores per-tab engines', async t => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'search-router-'));
  const registry = new EngineRegistry();
  for (const id of ['first', 'second', 'failed']) registry.register(id, () => new ChromiumAdapter({ id, directory: path.join(directory, id), ...(id === 'failed' ? { executablePath: '/missing/chromium' } : {}) }));
  let browser = new Browser({ registry, engine: 'first', store: new Store(directory), liveRouting: true });
  await browser.start();
  t.after(async () => { await browser.stop(); await rm(directory, { recursive: true, force: true }); });
  const ask = request => browser.execute(request);
  const original = browser.active;
  await ask({ do: 'eval', id: original, js: 'window.liveIdentity={count:41};document.body.innerHTML="<input type=password value=fake-secret>"' });
  const privateTab = (await ask({ do: 'open', private: true })).id;
  await ask({ do: 'eval', id: privateTab, js: 'window.privateIdentity="still-here"' });
  const result = await ask({ do: 'renderer-set', engine: 'second' });
  assert.equal(result.reloaded, false);
  assert.equal(await ask({ do: 'eval', id: original, js: '++window.liveIdentity.count' }), 42);
  assert.equal(await ask({ do: 'eval', id: original, js: 'document.querySelector("input").value' }), 'fake-secret');
  assert.equal(await ask({ do: 'eval', id: privateTab, js: 'window.privateIdentity' }), 'still-here');
  const newTab = (await ask({ do: 'open' })).id;
  assert.equal(browser.tab(newTab).engine, 'second');
  assert.equal(browser.tab(original).engine, 'first');
  assert.equal(await ask({ do: 'eval', id: newTab, js: 'typeof window.liveIdentity' }), 'undefined');
  await assert.rejects(ask({ do: 'renderer-set', engine: 'failed' }), { code: 'ENGINE_START_FAILED' });
  assert.equal(browser.engine, 'second');
  assert.equal(await ask({ do: 'eval', id: original, js: 'window.liveIdentity.count' }), 42);
  const mapping = await ask({ do: 'renderer-map' });
  assert.ok(mapping.some(item => item.id === original && item.engine === 'first'));
  assert.ok(mapping.some(item => item.id === newTab && item.engine === 'second'));
  await assert.rejects(ask({ do: 'engine', engine: 'first', reload: true }), { code: 'MIXED_RENDERERS' });
  await browser.stop();
  browser = new Browser({ registry, engine: 'first', store: new Store(directory), liveRouting: true });
  await browser.start();
  await ask({ do: 'select', id: original });
  await ask({ do: 'select', id: newTab });
  assert.equal(browser.adapter.host(original).id, 'first');
  assert.equal(browser.adapter.host(newTab).id, 'second');
  assert.ok(!browser.tabs.some(tab => tab.id === privateTab));
});
